enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  bookoo:
    npmRegistryServer: "https://registry.yarnpkg.com"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.6.4.cjs
